# Generated by Django 4.0.6 on 2022-07-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
