# Generated by Django 4.0.6 on 2022-07-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0003_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
