# Generated by Django 4.0.6 on 2022-07-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0006_usercredential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredential',
            name='id',
        ),
        migrations.AlterField(
            model_name='usercredential',
            name='user_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
