# Generated by Django 4.0.6 on 2022-07-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0007_remove_usercredential_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCredential',
            new_name='UserDetails',
        ),
    ]
