# Generated by Django 4.0.6 on 2022-07-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0009_usercredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(default='User', max_length=200),
        ),
    ]
